# Generated by Django 3.2.12 on 2022-10-28 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarly_articles', '0007_auto_20221022_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawunpaywall',
            name='resource_type',
            field=models.CharField(blank=True, choices=[('', 'NOT APPLICABLE'), ('book', 'Book'), ('book-chapter', 'Book Chapter'), ('book-part', 'Part'), ('book-section', 'Book Section'), ('book-series', 'Book Series'), ('book-set', 'Book Set'), ('book-track', 'Book Track'), ('component', 'Component'), ('database', 'Banco de dados'), ('dataset', 'Dataset'), ('dissertation', 'Dissertation'), ('edited-book', 'Edited Book'), ('grant', 'Grant'), ('journal', 'Journal'), ('journal-article', 'Journal Article'), ('journal-issue', 'Journal Issue'), ('journal-volume', 'Journal Volume'), ('monograph', 'Monograph'), ('other', 'Other'), ('peer-review', 'Peer Review'), ('posted-content', 'Posted Content'), ('proceedings', 'Proceedings'), ('proceedings-article', 'Proceedings Article'), ('proceedings-series', 'Proceedings Series'), ('reference-book', 'Reference Book'), ('reference-entry', 'Reference Entry'), ('report', 'Report'), ('report-component', 'Report Component'), ('report-series', 'Report Series'), ('standard', 'Standard'), ('standard-series', 'Standard Series')], max_length=50, verbose_name='Tipo de recurso'),
        ),
    ]
