# Generated by Django 3.2.12 on 2022-10-21 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure_directory', '0002_alter_infrastructuredirectory_record_status'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='infrastructuredirectory',
            index=models.Index(fields=['title'], name='infrastruct_title_169394_idx'),
        ),
        migrations.AddIndex(
            model_name='infrastructuredirectory',
            index=models.Index(fields=['practice'], name='infrastruct_practic_837632_idx'),
        ),
        migrations.AddIndex(
            model_name='infrastructuredirectory',
            index=models.Index(fields=['action'], name='infrastruct_action__7767ea_idx'),
        ),
        migrations.AddIndex(
            model_name='infrastructuredirectory',
            index=models.Index(fields=['classification'], name='infrastruct_classif_4340e3_idx'),
        ),
        migrations.AddIndex(
            model_name='infrastructuredirectory',
            index=models.Index(fields=['source'], name='infrastruct_source_43c6aa_idx'),
        ),
        migrations.AddIndex(
            model_name='infrastructuredirectory',
            index=models.Index(fields=['record_status'], name='infrastruct_record__60bb81_idx'),
        ),
    ]
