# Generated by Django 3.2.12 on 2022-10-28 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='indicator',
            name='indicator_i_compute_fecea6_idx',
        ),
    ]
