# Generated by Django 3.2.12 on 2022-10-25 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0006_auto_20220927_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='versioning',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='versioning',
            name='posterior_record',
        ),
        migrations.RemoveField(
            model_name='versioning',
            name='previous_record',
        ),
        migrations.RemoveField(
            model_name='versioning',
            name='updated_by',
        ),
        migrations.RenameField(
            model_name='indicator',
            old_name='file_json',
            new_name='computed',
        ),
        migrations.RenameField(
            model_name='indicator',
            old_name='file_csv',
            new_name='raw_data',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='versioning',
        ),
        migrations.AddField(
            model_name='indicator',
            name='code',
            field=models.CharField(default='', max_length=555, verbose_name='Código'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indicator',
            name='measurement',
            field=models.CharField(choices=[('', ''), ('FREQUENCY', 'Frequência'), ('EVOLUTION', 'Evolução'), ('AVERAGE', 'Média'), ('PERCENTUAL', 'Percentual')], max_length=25, null=True, verbose_name='Measurement'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='posterior_record',
            field=models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='successor_register', to='indicator.indicator', verbose_name='Posterior Record'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='previous_record',
            field=models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predecessor_register', to='indicator.indicator', verbose_name='Previous Record'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='scope',
            field=models.CharField(choices=[('', ''), ('INSTITUTIONAL', 'Instituticional'), ('GEOGRAPHIC', 'Geográfico'), ('CHRONOLOGICAL', 'Cronológico'), ('THEMATIC', 'Temático')], max_length=20, null=True, verbose_name='Scope'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='seq',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sequential number'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='total',
            field=models.IntegerField(default=None, null=True, verbose_name='Observations number'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='validity',
            field=models.CharField(blank=True, choices=[('', ''), ('CURRENT', 'CURRENT'), ('OUTDATED', 'OUTDATED')], max_length=255, null=True, verbose_name='Record validity'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='classification',
            field=models.CharField(blank=True, choices=[('', ''), ('curso livre', 'curso livre'), ('disciplina de graduação', 'disciplina de graduação'), ('disciplina de lato sensu', 'disciplina de lato sensu'), ('disciplina de stricto sensu', 'disciplina de stricto sensu'), ('encontro', 'encontro'), ('conferência', 'conferência'), ('congresso', 'congresso'), ('workshop', 'workshop'), ('seminário', 'seminário'), ('outros', 'outros'), ('portal', 'Portal'), ('plataforma', 'Plataforma'), ('servidor', 'Servidor'), ('repositório', 'Repositório'), ('serviço', 'Serviço'), ('promoção', 'promoção'), ('posicionamento', 'posicionamento'), ('mandato', 'mandato'), ('geral', 'geral'), ('outras', 'Outras')], max_length=255, null=True, verbose_name='Classificação'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='record_status',
            field=models.CharField(blank=True, choices=[('', ''), ('WIP', 'WORK IN PROGRESS'), ('TO MODERATE', 'TO MODERATE'), ('PUBLISHED', 'PUBLISHED')], max_length=255, null=True, verbose_name='Record status'),
        ),
        migrations.AddIndex(
            model_name='indicator',
            index=models.Index(fields=['classification'], name='indicator_i_classif_5f2684_idx'),
        ),
        migrations.AddIndex(
            model_name='indicator',
            index=models.Index(fields=['source'], name='indicator_i_source_d3cea0_idx'),
        ),
        migrations.AddIndex(
            model_name='indicator',
            index=models.Index(fields=['record_status'], name='indicator_i_record__612ab1_idx'),
        ),
        migrations.DeleteModel(
            name='Versioning',
        ),
    ]
