# Generated by Django 3.2.12 on 2022-10-21 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_directory', '0002_alter_eventdirectory_record_status'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='eventdirectory',
            index=models.Index(fields=['title'], name='event_direc_title_b42810_idx'),
        ),
        migrations.AddIndex(
            model_name='eventdirectory',
            index=models.Index(fields=['start_date'], name='event_direc_start_d_0d84ee_idx'),
        ),
        migrations.AddIndex(
            model_name='eventdirectory',
            index=models.Index(fields=['end_date'], name='event_direc_end_dat_aaef8c_idx'),
        ),
        migrations.AddIndex(
            model_name='eventdirectory',
            index=models.Index(fields=['practice'], name='event_direc_practic_716f65_idx'),
        ),
        migrations.AddIndex(
            model_name='eventdirectory',
            index=models.Index(fields=['action'], name='event_direc_action__072d36_idx'),
        ),
        migrations.AddIndex(
            model_name='eventdirectory',
            index=models.Index(fields=['classification'], name='event_direc_classif_7b57b2_idx'),
        ),
        migrations.AddIndex(
            model_name='eventdirectory',
            index=models.Index(fields=['source'], name='event_direc_source_9821a6_idx'),
        ),
        migrations.AddIndex(
            model_name='eventdirectory',
            index=models.Index(fields=['record_status'], name='event_direc_record__cc308f_idx'),
        ),
    ]
