# Generated by Django 3.2.12 on 2022-10-21 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_directory', '0002_alter_educationdirectory_record_status'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='educationdirectory',
            index=models.Index(fields=['title'], name='education_d_title_d46e56_idx'),
        ),
        migrations.AddIndex(
            model_name='educationdirectory',
            index=models.Index(fields=['start_date'], name='education_d_start_d_69988c_idx'),
        ),
        migrations.AddIndex(
            model_name='educationdirectory',
            index=models.Index(fields=['end_date'], name='education_d_end_dat_608248_idx'),
        ),
        migrations.AddIndex(
            model_name='educationdirectory',
            index=models.Index(fields=['practice'], name='education_d_practic_732278_idx'),
        ),
        migrations.AddIndex(
            model_name='educationdirectory',
            index=models.Index(fields=['action'], name='education_d_action__76539a_idx'),
        ),
        migrations.AddIndex(
            model_name='educationdirectory',
            index=models.Index(fields=['classification'], name='education_d_classif_d8755b_idx'),
        ),
        migrations.AddIndex(
            model_name='educationdirectory',
            index=models.Index(fields=['source'], name='education_d_source_a356a6_idx'),
        ),
        migrations.AddIndex(
            model_name='educationdirectory',
            index=models.Index(fields=['record_status'], name='education_d_record__4a0dd9_idx'),
        ),
    ]
